# REF: https://github.com/kentaro-m/auto-assign/

# This assigns a PR to its author
addAssignees: author

reviewers:
  # The default reviewers
  defaults:
    - maintainers

  groups:
    maintainers:
      - BrianLusina

# Set to true to add reviewers to pull requests
options:
  ignore_draft: true
  ignored_keywords:
    - WIP
    - wip
    - DO NOT MERGE
  enable_group_assignment: true
  number_of_reviewers: 1