import unittest
from typing import List
from parameterized import parameterized
from algorithms.graphs.reconstruct_itinerary import (
    find_itinerary,
    find_itinerary_using_hierholzers,
)

RECONSTRUCT_ITINERARY_TEST_CASES = [
    ([["JFK", "EDU"], ["EDU", "LEX"], ["LEX", "MUO"]], ["JFK", "EDU", "LEX", "MUO"]),
    (
        [["JFK", "XXX"], ["JFK", "YYY"], ["YYY", "ZZZ"], ["ZZZ", "JFK"]],
        ["JFK", "YYY", "ZZZ", "JFK", "XXX"],
    ),
    (
        [
            ["JFK", "COA"],
            ["JFK", "WAT"],
            ["WAT", "COA"],
            ["COA", "JFK"],
            ["COA", "WAT"],
        ],
        ["JFK", "COA", "JFK", "WAT", "COA", "WAT"],
    ),
    ([["JFK", "IDN"]], ["JFK", "IDN"]),
    (
        [
            ["JFK", "MLW"],
            ["MLW", "XKB"],
            ["XKB", "RUE"],
            ["RUE", "QNW"],
            ["QNW", "DJC"],
            ["DJC", "RUK"],
            ["RUK", "RCE"],
            ["RCE", "YAM"],
            ["YAM", "KGF"],
            ["KGF", "QRH"],
            ["QRH", "PDB"],
            ["PDB", "GSR"],
            ["GSR", "HZY"],
            ["HZY", "REC"],
            ["REC", "CKI"],
            ["CKI", "UEI"],
            ["UEI", "LWM"],
        ],
        [
            "JFK",
            "MLW",
            "XKB",
            "RUE",
            "QNW",
            "DJC",
            "RUK",
            "RCE",
            "YAM",
            "KGF",
            "QRH",
            "PDB",
            "GSR",
            "HZY",
            "REC",
            "CKI",
            "UEI",
            "LWM",
        ],
    ),
    (
        [
            ["JFK", "QBO"],
            ["QBO", "KLY"],
            ["KLY", "XBB"],
            ["XBB", "WFV"],
            ["WFV", "WXC"],
            ["WXC", "HKJ"],
            ["HKJ", "YLK"],
            ["YLK", "LIG"],
            ["LIG", "GHX"],
            ["GHX", "VJQ"],
            ["VJQ", "XBR"],
            ["XBR", "PJU"],
            ["PJU", "ITU"],
            ["ITU", "XTP"],
            ["XTP", "POX"],
            ["POX", "NZI"],
            ["NZI", "PVZ"],
            ["PVZ", "WGI"],
            ["WGI", "GNJ"],
            ["GNJ", "LIE"],
            ["LIE", "GPA"],
            ["GPA", "RJE"],
            ["RJE", "LBQ"],
            ["LBQ", "ELU"],
            ["ELU", "PEI"],
            ["PEI", "QVO"],
            ["QVO", "ADZ"],
            ["ADZ", "STH"],
            ["STH", "DCT"],
            ["DCT", "OSB"],
            ["OSB", "BIG"],
            ["BIG", "KOH"],
            ["KOH", "QDJ"],
        ],
        [
            "JFK",
            "QBO",
            "KLY",
            "XBB",
            "WFV",
            "WXC",
            "HKJ",
            "YLK",
            "LIG",
            "GHX",
            "VJQ",
            "XBR",
            "PJU",
            "ITU",
            "XTP",
            "POX",
            "NZI",
            "PVZ",
            "WGI",
            "GNJ",
            "LIE",
            "GPA",
            "RJE",
            "LBQ",
            "ELU",
            "PEI",
            "QVO",
            "ADZ",
            "STH",
            "DCT",
            "OSB",
            "BIG",
            "KOH",
            "QDJ",
        ],
    ),
    (
        [
            ["JFK", "OBU"],
            ["OBU", "JFK"],
            ["JFK", "KNJ"],
            ["KNJ", "JFK"],
            ["JFK", "FBF"],
            ["FBF", "JFK"],
            ["JFK", "SXL"],
            ["SXL", "JFK"],
            ["JFK", "UND"],
            ["UND", "JFK"],
            ["JFK", "HKO"],
            ["HKO", "JFK"],
            ["JFK", "IUB"],
            ["IUB", "JFK"],
            ["JFK", "LOG"],
            ["LOG", "JFK"],
            ["JFK", "NRN"],
            ["NRN", "JFK"],
            ["JFK", "YUU"],
            ["YUU", "JFK"],
            ["JFK", "VKL"],
            ["VKL", "JFK"],
            ["JFK", "LWE"],
            ["LWE", "JFK"],
        ],
        [
            "JFK",
            "FBF",
            "JFK",
            "HKO",
            "JFK",
            "IUB",
            "JFK",
            "KNJ",
            "JFK",
            "LOG",
            "JFK",
            "LWE",
            "JFK",
            "NRN",
            "JFK",
            "OBU",
            "JFK",
            "SXL",
            "JFK",
            "UND",
            "JFK",
            "VKL",
            "JFK",
            "YUU",
            "JFK",
        ],
    ),
    (
        [
            ["JFK", "SFO"],
            ["JFK", "ATL"],
            ["SFO", "ATL"],
            ["ATL", "JFK"],
            ["ATL", "SFO"],
        ],
        ["JFK", "ATL", "JFK", "SFO", "ATL", "SFO"],
    ),
]


class ReconstructItineraryTestCases(unittest.TestCase):
    @parameterized.expand(RECONSTRUCT_ITINERARY_TEST_CASES)
    def test_find_itinerary(self, tickets: List[List[str]], expected: List[str]):
        actual = find_itinerary(tickets)
        self.assertEqual(expected, actual)

    @parameterized.expand(RECONSTRUCT_ITINERARY_TEST_CASES)
    def test_find_itinerary_using_hierholzers(
        self, tickets: List[List[str]], expected: List[str]
    ):
        actual = find_itinerary_using_hierholzers(tickets)
        self.assertEqual(expected, actual)


if __name__ == "__main__":
    unittest.main()
