name: Lint

on:
  - push
  - pull_request

permissions:
  contents: read
  pull-requests: read

jobs:
  lint-ruff:
    strategy:
      matrix:
        python-version: [ '3.12' ]
    name: Pylint
    uses: SanctumLabs/ci-workflows/.github/workflows/python-lint-ruff.yml@main
    with:
      command: check
      python-version: ${{ matrix.python-version }}
      packager: poetry
